import { useCallback, useEffect, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useTranslation } from 'react-i18next';
import * as Haptics from 'expo-haptics';
import { ScreenContainer, PrimaryButton } from '@/components';
import { seedToWords } from '@/services/wallet';
import { DfxColors, Typography } from '@/theme';

const VERIFY_COUNT = 4;

function getRandomIndices(total: number, count: number): number[] {
  const indices: number[] = [];
  while (indices.length < count) {
    const idx = Math.floor(Math.random() * total);
    if (!indices.includes(idx)) indices.push(idx);
  }
  return indices.sort((a, b) => a - b);
}

/**
 * Uniform Fisher-Yates shuffle. The previous `arr.sort(() => Math.random() - 0.5)`
 * produces a non-uniform distribution (some permutations appear far more
 * often than others), which would let an attacker who can observe many
 * verifications guess the correct option from positional bias alone.
 */
function shuffle<T>(arr: T[]): T[] {
  const out = arr.slice();
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    // eslint-disable-next-line security/detect-object-injection -- both i and j are bounded by out.length
    [out[i], out[j]] = [out[j]!, out[i]!];
  }
  return out;
}

export default function VerifySeedScreen() {
  const router = useRouter();
  const { t } = useTranslation();
  const { seed } = useLocalSearchParams<{ seed: string }>();
  const seedWords = seedToWords(seed ?? '');

  const [verifyIndices] = useState(() => getRandomIndices(seedWords.length, VERIFY_COUNT));
  const [currentStep, setCurrentStep] = useState(0);
  const [selectedWord, setSelectedWord] = useState<string | null>(null);
  const [error, setError] = useState(false);

  // eslint-disable-next-line security/detect-object-injection -- currentStep is bounded to [0, VERIFY_COUNT) and verifyIndices.length === VERIFY_COUNT
  const currentIndex = verifyIndices[currentStep]!;
  // eslint-disable-next-line security/detect-object-injection -- currentIndex was generated by getRandomIndices(seedWords.length, ...) so it's a valid seedWords index
  const correctWord = seedWords[currentIndex]!;

  const getOptions = useCallback(() => {
    const options = [correctWord];
    while (options.length < 4) {
      // Random index is in [0, seedWords.length) so the lookup always yields a word.
      const randomWord = seedWords[Math.floor(Math.random() * seedWords.length)]!;
      if (!options.includes(randomWord)) options.push(randomWord);
    }
    return shuffle(options);
  }, [correctWord, seedWords]);

  const [options] = useState(getOptions);

  // Track outstanding timers so an unmount mid-animation doesn't fire a
  // setState on a stale component (warning + memory leak).
  const timersRef = useRef<ReturnType<typeof setTimeout>[]>([]);
  useEffect(() => {
    const timers = timersRef.current;
    return () => {
      timers.forEach(clearTimeout);
      timers.length = 0;
    };
  }, []);

  const handleSelect = (word: string) => {
    setSelectedWord(word);
    setError(false);

    if (word === correctWord) {
      void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      if (currentStep < VERIFY_COUNT - 1) {
        timersRef.current.push(
          setTimeout(() => {
            setCurrentStep((s) => s + 1);
            setSelectedWord(null);
          }, 500),
        );
      }
    } else {
      void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
      setError(true);
      timersRef.current.push(
        setTimeout(() => {
          setSelectedWord(null);
          setError(false);
        }, 1000),
      );
    }
  };

  const isComplete = currentStep === VERIFY_COUNT - 1 && selectedWord === correctWord;

  return (
    <ScreenContainer>
      <View style={styles.content}>
        <Text style={styles.title}>{t('onboarding.verifySeed')}</Text>
        <Text style={styles.description}>
          Select word #{currentIndex + 1} from your seed phrase.
        </Text>

        <View style={styles.progress}>
          {verifyIndices.map((_, i) => (
            <View
              key={i}
              style={[
                styles.progressDot,
                i < currentStep && styles.progressComplete,
                i === currentStep && styles.progressActive,
              ]}
            />
          ))}
        </View>

        <View style={styles.wordNumber}>
          <Text style={styles.wordNumberText}>Word #{currentIndex + 1}</Text>
        </View>

        <View style={styles.options}>
          {options.map((word) => {
            const isSelected = selectedWord === word;
            const isCorrect = isSelected && word === correctWord;
            const isWrong = isSelected && error;

            return (
              <Pressable
                key={word}
                style={[
                  styles.option,
                  isCorrect && styles.optionCorrect,
                  isWrong && styles.optionError,
                ]}
                onPress={() => handleSelect(word)}
                disabled={selectedWord !== null}
              >
                <Text
                  style={[
                    styles.optionText,
                    isCorrect && styles.optionTextCorrect,
                    isWrong && styles.optionTextError,
                  ]}
                >
                  {word}
                </Text>
              </Pressable>
            );
          })}
        </View>

        <View style={styles.spacer} />

        <PrimaryButton
          title={t('common.continue')}
          onPress={() => router.push('/(onboarding)/setup-pin')}
          disabled={!isComplete}
        />
      </View>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  content: {
    flex: 1,
    paddingVertical: 24,
    gap: 24,
  },
  title: {
    ...Typography.headlineMedium,
    color: DfxColors.text,
  },
  description: {
    ...Typography.bodyLarge,
    color: DfxColors.textSecondary,
  },
  progress: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
  },
  progressDot: {
    width: 32,
    height: 4,
    borderRadius: 2,
    backgroundColor: DfxColors.surfaceLight,
  },
  progressComplete: {
    backgroundColor: DfxColors.success,
  },
  progressActive: {
    backgroundColor: DfxColors.primary,
  },
  wordNumber: {
    alignSelf: 'center',
    backgroundColor: DfxColors.surface,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 24,
  },
  wordNumberText: {
    ...Typography.headlineSmall,
    color: DfxColors.text,
  },
  options: {
    gap: 12,
  },
  option: {
    padding: 16,
    borderRadius: 12,
    backgroundColor: DfxColors.surface,
    alignItems: 'center',
  },
  optionCorrect: {
    backgroundColor: DfxColors.success,
  },
  optionError: {
    backgroundColor: DfxColors.error,
  },
  optionText: {
    ...Typography.bodyLarge,
    color: DfxColors.text,
    fontWeight: '600',
  },
  optionTextCorrect: {
    color: DfxColors.black,
  },
  optionTextError: {
    color: DfxColors.white,
  },
  spacer: {
    flex: 1,
  },
});
