/**
 * Structured logging for hardware-wallet flows.
 *
 * The goal: enough context to debug a production issue without ever
 * including a key, password, passphrase, seed, or signature byte. The
 * logger redacts known-sensitive fields by name, and runs every emitted
 * payload through a final `redactBytes()` pass that strips anything that
 * smells like raw key material (long hex strings, byte arrays of
 * cryptographic length, EIP-712 typed-data payloads).
 *
 * In production: emits via console.info (and is collected by whatever
 * the host wallet's log aggregator uses).
 *
 * In tests: replace via setHwLogger() to capture entries for assertions.
 */

export type HwLogLevel = 'debug' | 'info' | 'warn' | 'error';

export type HwLogEntry = {
  level: HwLogLevel;
  msg: string;
  /** Arbitrary structured context. Redacted before emission. */
  ctx?: Record<string, unknown>;
  /** Per-flow correlation id. Generated by callers; not collected here. */
  flowId?: string;
  /** Timestamp at emission, ISO 8601. */
  ts: string;
};

export interface HwLogger {
  log(entry: Omit<HwLogEntry, 'ts'>): void;
}

const REDACTED = '[REDACTED]';

/**
 * Field names whose values should never be logged. Match is
 * case-insensitive and matches whole keys.
 */
const SENSITIVE_KEYS = new Set([
  'seed',
  'mnemonic',
  'password',
  'passphrase',
  'pin',
  'pincode',
  'pin_code',
  'privatekey',
  'private_key',
  'secret',
  'signature',
  'sig',
  'sigr',
  'sigs',
  'sigv',
  'r',
  's',
  'v',
  'message',
  'msg',
  'data',
  'rlppayload',
  'rlp_payload',
  'authcode',
  'auth_code',
  'token',
  'bearer',
  'cookie',
  'apikey',
  'api_key',
  'derivationpath',
  'derivation_path',
  'keypath',
  'address',
  'recipient',
  'from',
  'to',
]);

/** Substrings whose containing-string we replace entirely. */
const SENSITIVE_VALUE_PATTERNS: RegExp[] = [
  /\b0x[a-fA-F0-9]{40}\b/, // EVM address
  /\b0x[a-fA-F0-9]{64,}\b/, // long hex (likely private key, signature, hash)
  /\bbc1[0-9a-z]{20,}\b/i, // bech32 address
  /\b(?:xprv|xpub|ypub|zpub|vpub)[A-Za-z0-9]{50,}\b/, // extended pubkey/privkey
];

/** Redact a single value (recursive). */
function redactValue(key: string | undefined, value: unknown): unknown {
  if (key && SENSITIVE_KEYS.has(key.toLowerCase())) return REDACTED;
  if (value === null || value === undefined) return value;
  if (typeof value === 'string') return redactString(value);
  if (typeof value === 'number' || typeof value === 'boolean') return value;
  if (typeof value === 'bigint') return value.toString();
  if (Array.isArray(value)) {
    // Long byte-array-like arrays are cryptographic material.
    if (value.length >= 16 && value.every((v) => typeof v === 'number' && v >= 0 && v <= 255)) {
      return `[${value.length}-byte buffer]`;
    }
    return value.map((v) => redactValue(undefined, v));
  }
  if (value instanceof Uint8Array) {
    return `[${value.length}-byte buffer]`;
  }
  if (value instanceof Error) {
    // Error message may itself contain sensitive substrings.
    return { name: value.name, message: redactString(value.message) };
  }
  if (typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      out[k] = redactValue(k, v);
    }
    return out;
  }
  return REDACTED;
}

function redactString(s: string): string {
  let out = s;
  for (const pat of SENSITIVE_VALUE_PATTERNS) {
    out = out.replace(pat, REDACTED);
  }
  return out;
}

class ConsoleHwLogger implements HwLogger {
  log(entry: Omit<HwLogEntry, 'ts'>): void {
    const safe: HwLogEntry = {
      level: entry.level,
      msg: entry.msg,
      ts: new Date().toISOString(),
    };
    if (entry.flowId !== undefined) safe.flowId = entry.flowId;
    if (entry.ctx !== undefined) {
      safe.ctx = redactValue(undefined, entry.ctx) as Record<string, unknown>;
    }
    const out = JSON.stringify(safe);
    switch (entry.level) {
      case 'error':
        // eslint-disable-next-line no-console
        console.error(out);
        break;
      case 'warn':
        // eslint-disable-next-line no-console
        console.warn(out);
        break;
      case 'debug':
        // eslint-disable-next-line no-console
        console.debug(out);
        break;
      default:
        // eslint-disable-next-line no-console
        console.info(out);
        break;
    }
  }
}

let currentLogger: HwLogger = new ConsoleHwLogger();

/** Replace the active logger. Tests pass a capturing fake; production
 *  flips to a structured collector during app boot. */
export function setHwLogger(logger: HwLogger): void {
  currentLogger = logger;
}

/** Convenience: emit one log entry through the active logger. */
export function logHw(level: HwLogLevel, msg: string, ctx?: Record<string, unknown>, flowId?: string): void {
  const entry: Omit<HwLogEntry, 'ts'> = { level, msg };
  if (ctx !== undefined) entry.ctx = ctx;
  if (flowId !== undefined) entry.flowId = flowId;
  currentLogger.log(entry);
}

/** Test-only: redactValue exposed for unit assertions. */
export function _redactValueForTest(key: string | undefined, value: unknown): unknown {
  return redactValue(key, value);
}
